/*	wx_reduce(accumulator_function, starting_value)
	
	The following will produce:
	reducing...
	reducing...
	reducing...
	reducing...
	reducing...
	reducing...
	reducing...
	reducing...
	reducing...
	reducing...
	reducing...
	45
	
	this only returns the final accumulated value once all values
	have been collected
*/

// What our observer should to during the Next, Error, and Complete calls.
var observer =	wx_observer(
/*next:		*/	show_debug_message, 
/*error:	*/	function(){}, 
/*complete: */	game_end);

wx_interval(5).pipe(
	
	wx_tap(function(){ show_debug_message("reducing..."); }),
	wx_take(10),
	wx_reduce(function(a, b){
		return a + b;	
	}, 0)
	
).subscribe(observer);